# Generated by Django 3.1.6 on 2021-02-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=100, unique=True)),
                ('ciudad', models.CharField(max_length=100, unique=True)),
                ('longitud', models.FloatField(unique=True)),
                ('latitud', models.FloatField(unique=True)),
                ('estado_geo', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
